name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
      run: |
        npm install
        npx webpack

    - name: Deploy to VPS
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -r ./dist ubuntu@<YOUR_VPS_IP>:/home/ubuntu/web/geo-game
      env:
        SSH_AUTH_SOCK: /tmp/ssh-agent.sock
